<?php
require __DIR__ . '/../src/Support.php';
require __DIR__ . '/../src/Proxy.php';
use PiDingding\Support;
function ok($x,$m){if(!$x) throw new Exception($m);}
$dir=sys_get_temp_dir().'/pdp_'.bin2hex(random_bytes(3)); mkdir($dir.'/a',0777,true);
file_put_contents($dir.'/projects.json', json_encode(['projects'=>[['id'=>'p1','name'=>'A','path'=>$dir.'/a']]]));
$s=new Support($dir.'/projects.json',$dir);
ok(count($s->projects())===1,'projects');
ok($s->project('A')['path']===$dir.'/a','project lookup');
file_put_contents($dir.'/x.jsonl', "{\"type\":\"session\",\"id\":\"abc\",\"cwd\":\"$dir/a\"}\n".json_encode(['type'=>'message','message'=>['role'=>'user','content'=>'hello']])."\n");
ok(count($s->sessions($dir.'/a'))===1,'sessions');
ok(array_key_exists('title',$s->sessions($dir.'/a')[0]),'session title');
$long=$s->sessions($dir.'/a')[0]['title']; ok(strlen($long)<100 && !str_contains($long,'[') && !str_contains($long,'{'),'short plain title');
$cmd=$s->buildPiCommand('echo',['--x']); ok($cmd[0]==='echo' && in_array('--x',$cmd),'command');
$stateFile=$dir.'/state.json';
file_put_contents($stateFile, json_encode(['u'=>['project'=>['name'=>'A','path'=>$dir.'/a'],'session'=>null]]));
$state=json_decode(file_get_contents($stateFile), true); ok($state['u']['project']['name']==='A','persistent state');
$text='@交互机器人 /projects'; ok(trim(preg_replace('/^@[^\\s\\/]+\\s*/u','',$text))==='/projects','mention prefix');
file_put_contents($dir.'/proxy-state.json', json_encode(['u'=>['project'=>['name'=>'A','path'=>$dir.'/a'],'session'=>['id'=>'abc','title'=>'t','file'=>$dir.'/x.jsonl']]]));
$proxy=new \PiDingding\Proxy($s,'pi',5,$dir.'/proxy-state.json');
$out=$proxy->handle('u','/history'); ok(str_contains($out,'hello'),'history output');
file_put_contents($dir.'/y.jsonl', "{\"type\":\"session\",\"id\":\"def\",\"cwd\":\"$dir/a\"}\n".json_encode(['type'=>'message','message'=>['role'=>'assistant','content'=>[['type'=>'thinking','thinking'=>'secret-plan'],['type'=>'toolCall','name'=>'bash','arguments'=>['command'=>'rm -rf /']],['type'=>'toolResult','content'=>'raw-output'],['type'=>'text','text'=>'Answer here']]]])."\n");
$h=$s->history($dir.'/y.jsonl');
ok(str_contains($h[0]['content'],'Answer here'),'keep text block');
ok(!str_contains(json_encode($h),'secret-plan'),'skip thinking');
ok(!str_contains(json_encode($h),'raw-output'),'skip tool result');
ok(!str_contains($h[0]['content'],'{'),'no json in history');
file_put_contents($dir.'/proxy-state.json', json_encode(['u'=>['project'=>['name'=>'A','path'=>$dir.'/a'],'session'=>['id'=>'def','title'=>'t','file'=>$dir.'/y.jsonl']]]));
$proxy2=new \PiDingding\Proxy($s,'pi',5,$dir.'/proxy-state.json');
$md=$proxy2->handle('u','/history');
ok(str_contains($md,'**'),'markdown history');
ok(!str_contains($md,'toolCall'),'no toolCall json in markdown');
echo "ok\n";
